"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['osam-clock.py']
DATA_FILES = []
OPTIONS = {'iconfile': '/Users/axh0191/workspaces/osam-clock/digital-clock.icns'}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
